//! `.zkbignore` conformance, with `git check-ignore` as the oracle.
//!
//! The fixture is generated by scripts/gen-gitignore-cases.sh, so every expected
//! verdict comes from git rather than from someone's reading of the manual. That
//! is the whole argument for copying gitignore instead of inventing a dialect:
//! the spec can be queried, so a claim of compatibility can be falsified.
//!
//! A failure here is a real divergence. Do not adjust the fixture to match the
//! implementation — regenerate it and fix the implementation.

const std = @import("std");
const testing = std.testing;
const zkb = @import("zkb");
const ignore = zkb.ignore;

const fixture = @embedFile("fixtures/gitignore-cases.txt");

const Case = struct {
    group: []const u8,
    rules: []const u8,
    is_dir: bool,
    path: []const u8,
    want_ignored: bool,
};

test "gitignore conformance against git check-ignore" {
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var group: []const u8 = "";
    var rules: std.ArrayList(u8) = .empty;
    var patterns: std.ArrayList(ignore.Pattern) = .empty;

    var total: usize = 0;
    var failed: usize = 0;
    var first_failures: std.ArrayList(u8) = .empty;

    var lines = std.mem.splitScalar(u8, fixture, '\n');
    while (lines.next()) |line| {
        if (line.len == 0 or line[0] == '#') continue;

        if (std.mem.startsWith(u8, line, "GROUP ")) {
            group = line["GROUP ".len..];
            rules = .empty;
            patterns = .empty;
            continue;
        }
        if (std.mem.startsWith(u8, line, "RULE ")) {
            try rules.appendSlice(arena, line["RULE ".len..]);
            try rules.append(arena, '\n');
            // Reparsed per rule rather than accumulated, because order matters
            // and the fixture lists rules in file order.
            patterns = .empty;
            try ignore.parseInto(arena, &patterns, "", rules.items);
            continue;
        }
        if (!std.mem.startsWith(u8, line, "CASE ")) continue;

        // CASE <0|1> <path> <ignore|keep>
        var it = std.mem.tokenizeScalar(u8, line["CASE ".len..], ' ');
        const dir_flag = it.next() orelse continue;
        const path = it.next() orelse continue;
        const verdict = it.next() orelse continue;

        const c: Case = .{
            .group = group,
            .rules = rules.items,
            .is_dir = dir_flag[0] == '1',
            .path = path,
            .want_ignored = std.mem.eql(u8, verdict, "ignore"),
        };

        const m: ignore.Matcher = .{ .patterns = patterns.items };
        const got = m.isIgnored(c.path, c.is_dir);

        total += 1;
        if (got != c.want_ignored) {
            failed += 1;
            if (failed <= 12) {
                try first_failures.print(arena, "  [{s}] rules={s} path={s}{s} want={s} got={s}\n", .{
                    c.group,
                    std.mem.trimEnd(u8, c.rules, "\n"),
                    c.path,
                    if (c.is_dir) "/" else "",
                    if (c.want_ignored) "ignore" else "keep",
                    if (got) "ignore" else "keep",
                });
            }
        }
    }

    std.debug.print("\n.zkbignore vs git check-ignore: {d} 例，{d} 不一致\n", .{ total, failed });
    if (failed != 0) std.debug.print("{s}", .{first_failures.items});

    // The fixture must actually have been read; an empty run would pass silently
    // and that is the failure mode a conformance test exists to prevent.
    try testing.expect(total >= 60);
    try testing.expectEqual(@as(usize, 0), failed);
}
